service: alarm-dealer-setter
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    AlarmDealerUsername: ${ssm:ALARM_DEALER_USERNAME}
    AlarmDealerPassword: ${ssm:ALARM_DEALER_PASSWORD}

plugins:
  - serverless-offline
  - serverless-plugin-chrome
  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  get:
    handler: handler.get
    memorySize: 1536MB
    timeout: 900
    events:
      - http:
          path: /setAlarm
          method: get
